// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbProvAPI2.Data;

namespace WebbProvAPI2.Migrations
{
    [DbContext(typeof(WebbProvAPI2Context))]
    partial class WebbProvAPI2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebbProvAPI.Models.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BgColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderFont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Paragraph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WebbProvAPI.Models.CreatedPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BgColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColorFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColorHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColorLeftbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColorRightbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTypeFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTypeHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTypeLeftbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTypeRightbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorLeftbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorRightbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("FontFooter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontLeftbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontMain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Footer")
                        .HasColumnType("bit");

                    b.Property<string>("FooterString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Header")
                        .HasColumnType("bit");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<bool>("Right")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreatedPages");
                });

            modelBuilder.Entity("WebbProvAPI.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("DocData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("WebbProvAPI.Models.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebbProvAPI.Models.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("LinkString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Video")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("WebbProvAPI2.Models.OtherArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtherArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
